# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ayuda",
            fields=[
                ("estado", models.BooleanField(default=True, help_text="Indica si el registro está activo.", verbose_name="Estado")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")),
                ("id_ayuda", models.AutoField(db_column="id_ayuda", primary_key=True, serialize=False)),
                ("id_modulo", models.IntegerField(db_column="id_modulo",verbose_name="Módulo")),
                ("pantalla", models.CharField(max_length=100, verbose_name="Pantalla")),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("contenido", models.TextField(verbose_name="Contenido")),
                ("icono", models.CharField(blank=True, max_length=50, null=True, verbose_name="Ícono")),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Ayuda",
                "verbose_name_plural": "Ayudas",
                "db_table": "ayuda",
                "ordering": ["id_modulo", "orden", "titulo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id_modulo", "pantalla"),
                        name="uk_ayuda_modulo_pantalla",
                    ),
                ],
            },
        ),

        migrations.RunSQL(
            sql="""
                ALTER TABLE ayuda
                ADD CONSTRAINT fk_ayuda_modulo
                FOREIGN KEY (id_modulo)
                REFERENCES modulo(id_modulo)
                ON UPDATE CASCADE
                ON DELETE RESTRICT;
            """,
            reverse_sql="""
                ALTER TABLE ayuda
                DROP FOREIGN KEY fk_ayuda_modulo;
            """,
        ),
    ]