# Generated by Django 6.0.6 on 2026-08-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayuda',
            options={'managed': False, 'ordering': ['modulo', 'orden', 'titulo'], 'verbose_name': 'Ayuda', 'verbose_name_plural': 'Ayudas'},
        ),
    ]
