# Generated by Django 6.0.6 on 2026-08-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
