# Generated by Django 6.0.6 on 2026-07-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='id_categoria', primary_key=True, serialize=False),
        ),
    ]
