# Generated by Django 6.0.6 on 2026-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_modulo', models.AutoField(db_column='id_modulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, db_column='icono', max_length=100, null=True, verbose_name='Icono')),
                ('ruta', models.CharField(blank=True, db_column='ruta', max_length=150, null=True, verbose_name='Ruta')),
                ('orden_menu', models.IntegerField(db_column='orden_menu', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulo',
                'ordering': ['orden_menu'],
                'managed': False,
            },
        ),
    ]
