# Generated by Django 6.0.6 on 2026-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTributaria',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_configuracion_tributaria', models.AutoField(db_column='id_configuracion_tributaria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
                ('porcentaje', models.DecimalField(db_column='porcentaje', decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('aplica_compras', models.BooleanField(db_column='aplica_compras', default=True, verbose_name='Aplica a compras')),
                ('aplica_ventas', models.BooleanField(db_column='aplica_ventas', default=True, verbose_name='Aplica a ventas')),
            ],
            options={
                'verbose_name': 'Configuración tributaria',
                'verbose_name_plural': 'Configuraciones tributarias',
                'db_table': 'configuracion_tributaria',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_modulo', models.AutoField(db_column='id_modulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, db_column='icono', max_length=100, null=True, verbose_name='Icono')),
                ('ruta', models.CharField(blank=True, db_column='ruta', max_length=150, null=True, verbose_name='Ruta')),
                ('orden_menu', models.IntegerField(db_column='orden_menu', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulo',
                'ordering': ['orden_menu'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_sucursal', models.AutoField(db_column='id_sucursal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('encargado', models.CharField(blank=True, db_column='encargado', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
    ]
