# Generated by Django 6.0.6 on 2026-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # La tabla configuracion_tributaria ya existe físicamente
            # en la base de datos, por lo que no se ejecuta ninguna
            # operación SQL para crearla.
            database_operations=[],

            # Se registra el modelo únicamente en el estado
            # de migraciones de Django.
            state_operations=[
                migrations.CreateModel(
                    name="ConfiguracionTributaria",
                    fields=[
                        (
                            "estado",
                            models.BooleanField(
                                default=True,
                                help_text="Indica si el registro está activo.",
                                verbose_name="Estado",
                            ),
                        ),
                        (
                            "fecha_creacion",
                            models.DateTimeField(
                                auto_now_add=True,
                                verbose_name="Fecha de creación",
                            ),
                        ),
                        (
                            "fecha_actualizacion",
                            models.DateTimeField(
                                auto_now=True,
                                verbose_name="Fecha de actualización",
                            ),
                        ),
                        (
                            "id_configuracion_tributaria",
                            models.AutoField(
                                db_column="id_configuracion_tributaria",
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                db_column="nombre",
                                max_length=100,
                                unique=True,
                                verbose_name="Nombre",
                            ),
                        ),
                        (
                            "descripcion",
                            models.CharField(
                                blank=True,
                                db_column="descripcion",
                                max_length=255,
                                null=True,
                                verbose_name="Descripción",
                            ),
                        ),
                        (
                            "porcentaje",
                            models.DecimalField(
                                db_column="porcentaje",
                                decimal_places=2,
                                max_digits=5,
                                verbose_name="Porcentaje",
                            ),
                        ),
                        (
                            "aplica_compras",
                            models.BooleanField(
                                db_column="aplica_compras",
                                default=True,
                                verbose_name="Aplica a compras",
                            ),
                        ),
                        (
                            "aplica_ventas",
                            models.BooleanField(
                                db_column="aplica_ventas",
                                default=True,
                                verbose_name="Aplica a ventas",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Configuración tributaria",
                        "verbose_name_plural": "Configuraciones tributarias",
                        "db_table": "configuracion_tributaria",
                    },
                ),
            ],
        ),
    ]