# Generated by Django 6.0.6 on 2026-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id_datos_empresa', models.AutoField(db_column='id_datos_empresa', primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(db_column='nombre_comercial', max_length=150, verbose_name='Nombre comercial')),
                ('cedula_juridica', models.CharField(db_column='cedula_juridica', max_length=30, verbose_name='Cédula jurídica')),
                ('regimen_tributario', models.CharField(blank=True, choices=[('TRADICIONAL', 'Régimen Tradicional (General)'), ('SIMPLIFICADO', 'Régimen de Tributación Simplificada (RTS)'), ('OTRO', 'Otro')], db_column='regimen_tributario', max_length=100, null=True, verbose_name='Régimen tributario')),
                ('direccion_fiscal', models.CharField(blank=True, db_column='direccion_fiscal', max_length=255, null=True, verbose_name='Dirección fiscal')),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=150, null=True, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
                'db_table': 'datos_empresa',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='configuraciontributaria',
            options={'managed': False, 'verbose_name': 'Configuración tributaria', 'verbose_name_plural': 'Configuraciones tributarias'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Método de pago', 'verbose_name_plural': 'Métodos de pago'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'managed': False, 'ordering': ['orden_menu'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False, 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
