# Generated by Django 6.0.6 on 2026-08-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
