# Generated by Django 6.0.6 on 2026-07-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_cargo', models.AutoField(db_column='id_cargo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_empleado', models.AutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('identificacion', models.CharField(db_column='identificacion', max_length=20, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido1', models.CharField(db_column='apellido1', max_length=100)),
                ('apellido2', models.CharField(blank=True, db_column='apellido2', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='fecha_ingreso', null=True)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
    ]
