# Generated by Django 6.0.6 on 2026-08-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': False, 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False, 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
