# Generated by Django 6.0.6 on 2026-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido1'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        # SeparateDatabaseAndState (06-08): 'tipo_cliente' y 'tipo_identificacion' ya existen
        # como columnas reales en la tabla 'cliente' (agregadas por fuera de Django, como
        # ENUM('FISICA','JURIDICA') / ENUM('CF','CJ','DIMEX','PASS') — confirmado con
        # DESCRIBE cliente; en MySQL antes de generar esta migración). Un AddField normal
        # aquí fallaría con "Duplicate column name". database_operations=[] hace que esta
        # migración NO ejecute ningún ALTER TABLE para estos dos campos — state_operations
        # solo actualiza el historial interno de Django para que quede sincronizado con la
        # realidad (y makemigrations deje de "detectarlos" como faltantes cada vez).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='cliente',
                    name='tipo_cliente',
                    field=models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], db_column='tipo_cliente', default='FISICA', max_length=10, verbose_name='Tipo de cliente'),
                ),
                migrations.AddField(
                    model_name='cliente',
                    name='tipo_identificacion',
                    field=models.CharField(choices=[('CF', 'Cédula Física'), ('CJ', 'Cédula Jurídica'), ('DIMEX', 'DIMEX'), ('PASS', 'Pasaporte')], db_column='tipo_identificacion', default='CF', max_length=10, verbose_name='Tipo de identificación'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(blank=True, db_column='apellido1', max_length=100, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(blank=True, db_column='apellido2', max_length=100, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(db_column='correo', default='sin-dato@sigepan.local', max_length=150, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, db_column='direccion', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(db_column='id_cliente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(db_column='identificacion', default='pendiente', max_length=20, unique=True, verbose_name='Identificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(db_column='nombre', default='pendiente', max_length=100, verbose_name='Nombre / Razón Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(db_column='telefono', default='pendiente', max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
