# Generated by Django 6.0.6 on 2026-08-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'ordering': ['nombre', 'apellido1'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
