# Generated by Django 6.0.6 on 2026-07-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_permiso', models.AutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('accion', models.CharField(db_column='accion', max_length=50, verbose_name='Acción')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'ordering': ['accion'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.AutoField(db_column='id_rol_permiso', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.DO_NOTHING, to='security.permiso', verbose_name='Permiso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='security.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol - Permiso',
                'verbose_name_plural': 'Roles - Permisos',
                'db_table': 'rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=150, null=True, unique=True)),
                ('google_email', models.CharField(blank=True, db_column='google_email', max_length=150, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, db_column='google_id', max_length=150, null=True)),
                ('google_token', models.TextField(blank=True, db_column='google_token', null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.empleado', verbose_name='Empleado')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='security.rol', verbose_name='Rol')),
                ('id_sucursal', models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='LogAcciones',
            fields=[
                ('id_log', models.AutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('CREAR', 'CREAR'), ('MODIFICAR', 'MODIFICAR'), ('ELIMINAR', 'ELIMINAR'), ('ACCESO_DENEGADO', 'ACCESO_DENEGADO')], db_column='tipo_accion', max_length=20)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=500)),
                ('ip_origen', models.CharField(blank=True, db_column='ip_origen', max_length=45, null=True)),
                ('navegador', models.CharField(blank=True, db_column='navegador', max_length=150, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='fecha_hora')),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.modulo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='security.usuario')),
            ],
            options={
                'verbose_name': 'Log de acciones',
                'verbose_name_plural': 'Logs de acciones',
                'db_table': 'log_acciones',
            },
        ),
    ]
