# Generated by Django 6.0.6 on 2026-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_refresh_token',
            field=models.TextField(blank=True, db_column='google_refresh_token', null=True),
        ),
    ]
