# Generated by Django 6.0.6 on 2026-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo.', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_permiso', models.AutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('accion', models.CharField(db_column='accion', max_length=50, verbose_name='Acción')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'ordering': ['modulo', 'accion'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
