# Generated by Django 6.0.6 on 2026-07-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_normalizar_tipo_accion_enum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
