# Generated by Django 6.0.6 on 2026-08-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_usuario_google_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacciones',
            name='tipo_accion',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('CREAR', 'CREAR'), ('MODIFICAR', 'MODIFICAR'), ('ELIMINAR', 'ELIMINAR'), ('CONSULTAR', 'CONSULTAR'), ('EXPORTAR', 'EXPORTAR'), ('IMPORTAR', 'IMPORTAR'), ('ERROR', 'ERROR'), ('ACCESO_DENEGADO', 'ACCESO DENEGADO'), ('RECUPERAR_PASSWORD', 'RECUPERAR CONTRASEÑA'), ('CAMBIAR_PASSWORD', 'CAMBIAR CONTRASEÑA'), ('CAMBIAR_USUARIO', 'CAMBIAR USUARIO')], db_column='tipo_accion', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
    ]
