# Generated by Django 6.0.6 on 2026-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacciones',
            name='tipo_accion',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('CREAR', 'CREAR'), ('MODIFICAR', 'MODIFICAR'), ('ELIMINAR', 'ELIMINAR'), ('ACCESO_DENEGADO', 'ACCESO DENEGADO'), ('RECUPERAR_PASSWORD', 'RECUPERAR CONTRASEÑA'), ('CAMBIAR_PASSWORD', 'CAMBIAR CONTRASEÑA')], db_column='tipo_accion', max_length=20),
        ),
    ]
